-- Supabase schema + RLS for per-user candidates/resumes

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  icon text,
  department text,
  location text,
  type text,
  openings integer not null default 1 check (openings >= 1),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now()
);

create table if not exists public.candidates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  job_title text not null,
  stage text not null default 'Applied',
  email text,
  location text,
  years_experience numeric,
  skills text[] not null default '{}',
  education text[] not null default '{}',
  resume_path text,
  resume_preview_url text,
  ats_score numeric,
  analysis_summary text,
  analysis_strengths text[] not null default '{}',
  analysis_concerns text[] not null default '{}',
  ai_writing_score numeric,
  ai_writing_label text,
  ai_writing_notes text[] not null default '{}',
  interview_questions text[] not null default '{}',
  offer_summary text,
  offer_checklist jsonb not null default '{"interviewCompleted":false,"referencesChecked":false,"termsAligned":false,"internalApproval":false,"offerSent":false}'::jsonb,
  offer_outcome text not null default 'pending',
  offer_sent_at date,
  offer_response_due_at date,
  skill_profile jsonb,
  analysis_status text not null default 'pending_ai',
  interview_analysis_status text not null default 'none',
  interview_analysis_score numeric,
  interview_analysis_summary text,
  interview_analysis_strengths text[] not null default '{}',
  interview_analysis_concerns text[] not null default '{}',
  interview_analysis_questions text[] not null default '{}',
  interview_analysis_transcript_ids uuid[] not null default '{}',
  interview_analysis_updated_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.candidates
  add column if not exists interview_analysis_status text not null default 'none',
  add column if not exists interview_analysis_score numeric,
  add column if not exists interview_analysis_summary text,
  add column if not exists interview_analysis_strengths text[] not null default '{}',
  add column if not exists interview_analysis_concerns text[] not null default '{}',
  add column if not exists interview_analysis_questions text[] not null default '{}',
  add column if not exists interview_analysis_transcript_ids uuid[] not null default '{}',
  add column if not exists interview_analysis_updated_at timestamptz;

create table if not exists public.signup_rate_limits (
  id bigint generated by default as identity primary key,
  ip text not null,
  attempts int not null default 0,
  window_start timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.ai_agent_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  scoring_strictness text not null default 'balanced',
  response_tone text not null default 'professional',
  interview_question_style text not null default 'practical',
  ai_writing_sensitivity text not null default 'balanced',
  evaluation_focus text[] not null default '{}',
  custom_instructions text,
  updated_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create table if not exists public.offer_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  title text not null,
  content text not null,
  inputs jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  generated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text not null check (entity_type in ('candidate', 'job', 'offer_document')),
  entity_id uuid,
  entity_label text,
  from_value text,
  to_value text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.interview_studio_boards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Studio razgovorov',
  nodes jsonb not null default '[]'::jsonb,
  edges jsonb not null default '[]'::jsonb,
  transcripts jsonb not null default '[]'::jsonb,
  viewport jsonb not null default '{"x":-220,"y":-110,"zoom":1}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.interview_transcripts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  transcript_text text,
  audio_path text,
  audio_mime_type text,
  duration_seconds integer not null default 0 check (duration_seconds >= 0 and duration_seconds <= 3600),
  status text not null default 'recorded' check (status in ('recorded', 'processing', 'complete', 'failed')),
  source text not null default 'recording' check (source in ('recording', 'manual')),
  estimated_cost_usd numeric,
  actual_cost_usd numeric,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.candidate_interview_transcripts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  transcript_id uuid not null references public.interview_transcripts(id) on delete cascade,
  linked_at timestamptz not null default now(),
  unique (user_id, candidate_id, transcript_id),
  unique (user_id, transcript_id)
);

alter table public.jobs enable row level security;
alter table public.candidates enable row level security;
alter table public.signup_rate_limits enable row level security;
alter table public.ai_agent_settings enable row level security;
alter table public.offer_documents enable row level security;
alter table public.activity_logs enable row level security;
alter table public.interview_studio_boards enable row level security;
alter table public.interview_transcripts enable row level security;
alter table public.candidate_interview_transcripts enable row level security;

create policy "jobs_select_own" on public.jobs
  for select using (user_id = auth.uid());
create policy "jobs_insert_own" on public.jobs
  for insert with check (user_id = auth.uid());
create policy "jobs_update_own" on public.jobs
  for update using (user_id = auth.uid());
create policy "jobs_delete_own" on public.jobs
  for delete using (user_id = auth.uid());

create policy "candidates_select_own" on public.candidates
  for select using (user_id = auth.uid());
create policy "candidates_insert_own" on public.candidates
  for insert with check (user_id = auth.uid());
create policy "candidates_update_own" on public.candidates
  for update using (user_id = auth.uid());
create policy "candidates_delete_own" on public.candidates
  for delete using (user_id = auth.uid());

create policy "signup_rate_limits_no_access" on public.signup_rate_limits
  for all using (false);

create policy "ai_agent_settings_select_own" on public.ai_agent_settings
  for select using (user_id = auth.uid());
create policy "ai_agent_settings_insert_own" on public.ai_agent_settings
  for insert with check (user_id = auth.uid());
create policy "ai_agent_settings_update_own" on public.ai_agent_settings
  for update using (user_id = auth.uid());
create policy "ai_agent_settings_delete_own" on public.ai_agent_settings
  for delete using (user_id = auth.uid());

create policy "offer_documents_select_own" on public.offer_documents
  for select using (user_id = auth.uid());
create policy "offer_documents_insert_own" on public.offer_documents
  for insert with check (user_id = auth.uid());
create policy "offer_documents_update_own" on public.offer_documents
  for update using (user_id = auth.uid());
create policy "offer_documents_delete_own" on public.offer_documents
  for delete using (user_id = auth.uid());

create policy "activity_logs_select_own" on public.activity_logs
  for select using (user_id = auth.uid());
create policy "activity_logs_insert_own" on public.activity_logs
  for insert with check (user_id = auth.uid());

create policy "interview_studio_boards_select_own" on public.interview_studio_boards
  for select using (user_id = auth.uid());
create policy "interview_studio_boards_insert_own" on public.interview_studio_boards
  for insert with check (user_id = auth.uid());
create policy "interview_studio_boards_update_own" on public.interview_studio_boards
  for update using (user_id = auth.uid());
create policy "interview_studio_boards_delete_own" on public.interview_studio_boards
  for delete using (user_id = auth.uid());

create index if not exists interview_studio_boards_user_updated_at_idx
  on public.interview_studio_boards (user_id, updated_at desc);

create policy "interview_transcripts_select_own" on public.interview_transcripts
  for select using (user_id = auth.uid());
create policy "interview_transcripts_insert_own" on public.interview_transcripts
  for insert with check (user_id = auth.uid());
create policy "interview_transcripts_update_own" on public.interview_transcripts
  for update using (user_id = auth.uid());
create policy "interview_transcripts_delete_own" on public.interview_transcripts
  for delete using (user_id = auth.uid());

create index if not exists interview_transcripts_user_created_at_idx
  on public.interview_transcripts (user_id, created_at desc);
create index if not exists interview_transcripts_status_idx
  on public.interview_transcripts (user_id, status, updated_at desc);

create policy "candidate_interview_transcripts_select_own" on public.candidate_interview_transcripts
  for select using (user_id = auth.uid());
create policy "candidate_interview_transcripts_insert_own" on public.candidate_interview_transcripts
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.candidates
      where candidates.id = candidate_interview_transcripts.candidate_id
        and candidates.user_id = auth.uid()
    )
    and exists (
      select 1 from public.interview_transcripts
      where interview_transcripts.id = candidate_interview_transcripts.transcript_id
        and interview_transcripts.user_id = auth.uid()
    )
  );
create policy "candidate_interview_transcripts_update_own" on public.candidate_interview_transcripts
  for update using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.candidates
      where candidates.id = candidate_interview_transcripts.candidate_id
        and candidates.user_id = auth.uid()
    )
    and exists (
      select 1 from public.interview_transcripts
      where interview_transcripts.id = candidate_interview_transcripts.transcript_id
        and interview_transcripts.user_id = auth.uid()
    )
  );
create policy "candidate_interview_transcripts_delete_own" on public.candidate_interview_transcripts
  for delete using (user_id = auth.uid());

create index if not exists candidate_interview_transcripts_candidate_idx
  on public.candidate_interview_transcripts (user_id, candidate_id, linked_at desc);
create index if not exists candidate_interview_transcripts_transcript_idx
  on public.candidate_interview_transcripts (user_id, transcript_id);
create unique index if not exists candidate_interview_transcripts_one_candidate_per_transcript_idx
  on public.candidate_interview_transcripts (user_id, transcript_id);

insert into storage.buckets (id, name, public)
values ('interview-recordings', 'interview-recordings', false)
on conflict (id) do nothing;

create policy "interview_recordings_read_own" on storage.objects
  for select using (
    bucket_id = 'interview-recordings'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "interview_recordings_write_own" on storage.objects
  for insert with check (
    bucket_id = 'interview-recordings'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "interview_recordings_update_own" on storage.objects
  for update using (
    bucket_id = 'interview-recordings'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "interview_recordings_delete_own" on storage.objects
  for delete using (
    bucket_id = 'interview-recordings'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

insert into storage.buckets (id, name, public)
values ('resumes', 'resumes', false)
on conflict (id) do nothing;

create policy "resumes_read_own" on storage.objects
  for select using (
    bucket_id = 'resumes'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "resumes_write_own" on storage.objects
  for insert with check (
    bucket_id = 'resumes'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "resumes_update_own" on storage.objects
  for update using (
    bucket_id = 'resumes'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "resumes_delete_own" on storage.objects
  for delete using (
    bucket_id = 'resumes'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- If you already created the candidates table earlier, run this ALTER block:
-- alter table public.candidates
--   add column if not exists location text,
--   add column if not exists years_experience numeric,
--   add column if not exists skills text[] not null default '{}',
--   add column if not exists education text[] not null default '{}',
--   add column if not exists analysis_summary text,
--   add column if not exists analysis_strengths text[] not null default '{}',
--   add column if not exists analysis_concerns text[] not null default '{}',
--   add column if not exists ai_writing_score numeric,
--   add column if not exists ai_writing_label text,
--   add column if not exists ai_writing_notes text[] not null default '{}',
--   add column if not exists interview_questions text[] not null default '{}',
--   add column if not exists offer_summary text,
--   add column if not exists offer_checklist jsonb not null default '{"interviewCompleted":false,"referencesChecked":false,"termsAligned":false,"internalApproval":false,"offerSent":false}'::jsonb,
--   add column if not exists offer_outcome text not null default 'pending',
--   add column if not exists offer_sent_at date,
--   add column if not exists offer_response_due_at date,
--   add column if not exists skill_profile jsonb;

-- If you already created the jobs table earlier, run this ALTER block:
-- alter table public.jobs
--   add column if not exists description text;
--   add column if not exists icon text;
-- alter table public.jobs
--   add column if not exists openings integer not null default 1;
-- alter table public.jobs
--   add constraint jobs_openings_min check (openings >= 1);
-- alter table public.jobs
--   add column if not exists status text not null default 'active';
-- alter table public.jobs
--   add constraint jobs_status_check check (status in ('active', 'inactive'));

-- If you already created the schema earlier, run this block for AI agent settings:
-- create table if not exists public.ai_agent_settings (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users(id) on delete cascade,
--   job_id uuid not null references public.jobs(id) on delete cascade,
--   scoring_strictness text not null default 'balanced',
--   response_tone text not null default 'professional',
--   interview_question_style text not null default 'practical',
--   ai_writing_sensitivity text not null default 'balanced',
--   evaluation_focus text[] not null default '{}',
--   custom_instructions text,
--   updated_at timestamptz not null default now(),
--   unique (user_id, job_id)
-- );
-- alter table public.ai_agent_settings enable row level security;
-- create policy "ai_agent_settings_select_own" on public.ai_agent_settings
--   for select using (user_id = auth.uid());
-- create policy "ai_agent_settings_insert_own" on public.ai_agent_settings
--   for insert with check (user_id = auth.uid());
-- create policy "ai_agent_settings_update_own" on public.ai_agent_settings
--   for update using (user_id = auth.uid());
-- create policy "ai_agent_settings_delete_own" on public.ai_agent_settings
--   for delete using (user_id = auth.uid());

-- If you already created the schema earlier, run this block for offer documents:
-- create table if not exists public.offer_documents (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users(id) on delete cascade,
--   candidate_id uuid not null references public.candidates(id) on delete cascade,
--   title text not null,
--   content text not null,
--   inputs jsonb not null default '{}'::jsonb,
--   status text not null default 'draft',
--   generated_by uuid references auth.users(id) on delete set null,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now()
-- );
-- alter table public.offer_documents enable row level security;
-- create policy "offer_documents_select_own" on public.offer_documents
--   for select using (user_id = auth.uid());
-- create policy "offer_documents_insert_own" on public.offer_documents
--   for insert with check (user_id = auth.uid());
-- create policy "offer_documents_update_own" on public.offer_documents
--   for update using (user_id = auth.uid());
-- create policy "offer_documents_delete_own" on public.offer_documents
--   for delete using (user_id = auth.uid());
-- alter table public.offer_documents
--   add column if not exists inputs jsonb not null default '{}'::jsonb;

-- If you already created the schema earlier, run this block for activity logs:
-- create table if not exists public.activity_logs (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users(id) on delete cascade,
--   action text not null,
--   entity_type text not null check (entity_type in ('candidate', 'job', 'offer_document')),
--   entity_id uuid,
--   entity_label text,
--   from_value text,
--   to_value text,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamptz not null default now()
-- );
-- alter table public.activity_logs enable row level security;
-- create policy "activity_logs_select_own" on public.activity_logs
--   for select using (user_id = auth.uid());
-- create policy "activity_logs_insert_own" on public.activity_logs
--   for insert with check (user_id = auth.uid());

-- If you already created the schema earlier, run this block for the interview studio board:
-- create table if not exists public.interview_studio_boards (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users(id) on delete cascade,
--   title text not null default 'Studio razgovorov',
--   nodes jsonb not null default '[]'::jsonb,
--   edges jsonb not null default '[]'::jsonb,
--   transcripts jsonb not null default '[]'::jsonb,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   unique (user_id)
-- );
-- alter table public.interview_studio_boards enable row level security;
-- alter table public.interview_studio_boards
--   add column if not exists viewport jsonb not null default '{"x":-220,"y":-110,"zoom":1}'::jsonb;
-- create policy "interview_studio_boards_select_own" on public.interview_studio_boards
--   for select using (user_id = auth.uid());
-- create policy "interview_studio_boards_insert_own" on public.interview_studio_boards
--   for insert with check (user_id = auth.uid());
-- create policy "interview_studio_boards_update_own" on public.interview_studio_boards
--   for update using (user_id = auth.uid());
-- create policy "interview_studio_boards_delete_own" on public.interview_studio_boards
--   for delete using (user_id = auth.uid());
-- create index if not exists interview_studio_boards_user_updated_at_idx
--   on public.interview_studio_boards (user_id, updated_at desc);

-- If you already created the schema earlier, run this block for recorded interview transcripts:
-- create table if not exists public.interview_transcripts (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users(id) on delete cascade,
--   title text not null,
--   transcript_text text,
--   audio_path text,
--   audio_mime_type text,
--   duration_seconds integer not null default 0 check (duration_seconds >= 0 and duration_seconds <= 3600),
--   status text not null default 'recorded' check (status in ('recorded', 'processing', 'complete', 'failed')),
--   source text not null default 'recording' check (source in ('recording', 'manual')),
--   estimated_cost_usd numeric,
--   actual_cost_usd numeric,
--   error_message text,
--   metadata jsonb not null default '{}'::jsonb,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now()
-- );
-- alter table public.interview_transcripts enable row level security;
-- create policy "interview_transcripts_select_own" on public.interview_transcripts
--   for select using (user_id = auth.uid());
-- create policy "interview_transcripts_insert_own" on public.interview_transcripts
--   for insert with check (user_id = auth.uid());
-- create policy "interview_transcripts_update_own" on public.interview_transcripts
--   for update using (user_id = auth.uid());
-- create policy "interview_transcripts_delete_own" on public.interview_transcripts
--   for delete using (user_id = auth.uid());
-- create index if not exists interview_transcripts_user_created_at_idx
--   on public.interview_transcripts (user_id, created_at desc);
-- create index if not exists interview_transcripts_status_idx
--   on public.interview_transcripts (user_id, status, updated_at desc);
-- insert into storage.buckets (id, name, public)
-- values ('interview-recordings', 'interview-recordings', false)
-- on conflict (id) do nothing;
-- create policy "interview_recordings_read_own" on storage.objects
--   for select using (
--     bucket_id = 'interview-recordings'
--     and auth.uid()::text = (storage.foldername(name))[1]
--   );
-- create policy "interview_recordings_write_own" on storage.objects
--   for insert with check (
--     bucket_id = 'interview-recordings'
--     and auth.uid()::text = (storage.foldername(name))[1]
--   );
-- create policy "interview_recordings_update_own" on storage.objects
--   for update using (
--     bucket_id = 'interview-recordings'
--     and auth.uid()::text = (storage.foldername(name))[1]
--   );
-- create policy "interview_recordings_delete_own" on storage.objects
--   for delete using (
--     bucket_id = 'interview-recordings'
--     and auth.uid()::text = (storage.foldername(name))[1]
--   );
